version: '3'

services:

    app:
        container_name: fastapi_backend
        build:
            context: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        links:
            - "postgresql:postgresql"
        depends_on:
            - postgresql

    postgresql:
        image: postgres:14
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data/

    pgadmin:
        container_name: pg_admin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "80:80"
        depends_on:
            - postgresql

volumes:
    pgdata:
